spring.application.name=SpringBoot

#comments for application.properties

#database configuration

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://gateway01.us-west-2.prod.aws.tidbcloud.com:4000/test
spring.datasource.username=J3pzmwzFdbdz1YR.root
spring.datasource.password=SU6kDZn5h1m87coL

#JPA- Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true